services:
  data-commons-search:
    build: .
    # image: ghcr.io/eosc-data-commons/data-commons-search:main
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - keys.env
    volumes:
      - ./data:/app/data # For logs
