"""Generate the PostgreSQL schema files from the SQLAlchemy models in db.py.

The output is consumed by metadata-warehouse, which runs the files in a fixed order
(types.sql -> tables.sql -> indexes.sql, see scripts/postgres_data/create_db.py there).

Run with:
    uv run scripts/export_db_schema.py --out-dir ../metadata-warehouse/scripts/postgres_data/create_sql/appdb
    uv run scripts/export_db_schema.py schema.sql      # single file, tables only

Two metadata sets are rendered:
  - `Base`: the app tables owned and created by this service.
  - `SearchBase`: the hybrid search tables, owned and filled by index_datasets.py in
    metadata-warehouse and only read here. They are exported but never created by this service.
"""

import argparse
from pathlib import Path

from sqlalchemy import MetaData, Table
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from data_commons_search.db import (
    DATASET_EMBEDDING_FIELD_ENUM,
    DATASET_EMBEDDING_FIELDS,
    Base,
    SearchBase,
)

HEADER = (
    "-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.\n"
    "-- Generated by scripts/export_db_schema.py from\n"
    "-- https://github.com/EOSC-Data-Commons/data-commons-search/blob/main/src/data_commons_search/db.py\n"
)

# Extensions are provisioned outside the ORM (they are installed in the image built by
# docker/postgres/Dockerfile, and pg_textsearch also needs shared_preload_libraries), so this
# block has no counterpart in db.py and is emitted verbatim.
EXTENSIONS_SQL = """-- ============================================
-- EXTENSIONS
-- ============================================
-- Extensions used for hybrid search in postgres (installed in the image built by
-- docker/postgres/Dockerfile, pg_textsearch also needs shared_preload_libraries).

-- vector column type + HNSW/IVFFlat indexes
CREATE EXTENSION IF NOT EXISTS vector;

-- StreamingDiskANN index for vector similarity search (depends on vector)
CREATE EXTENSION IF NOT EXISTS vectorscale;

-- BM25 ranked full text search
CREATE EXTENSION IF NOT EXISTS pg_textsearch;"""

DIALECT = postgresql.dialect()


def render(element: CreateTable | CreateIndex) -> str:
    """Compile one DDL element.

    The compiler escapes `%` for the DBAPI paramstyle, which would leave `LIKE 'http%%'` in a
    file meant to be executed as plain SQL, so it is unescaped here.
    """
    sql = str(element.compile(dialect=DIALECT)).strip()
    return "\n".join(line.rstrip() for line in sql.splitlines()).replace("%%", "%")


def comments_sql(table: Table) -> list[str]:
    """COMMENT ON statements for a table and its columns (CreateTable does not emit them)."""
    statements = []
    if table.comment:
        statements.append(f"COMMENT ON TABLE {table.name} IS '{table.comment}';")
    statements += [
        f"COMMENT ON COLUMN {table.name}.{column.name} IS '{column.comment}';"
        for column in table.columns
        if column.comment
    ]
    return statements


def render_tables(*metadatas: MetaData) -> str:
    """CREATE TABLE + COMMENT ON for every table, in dependency order."""
    blocks = []
    for metadata in metadatas:
        for table in metadata.sorted_tables:
            block = render(CreateTable(table)) + ";"
            if comments := comments_sql(table):
                block += "\n\n" + "\n".join(comments)
            blocks.append(block)
    return HEADER + "\n" + "\n\n".join(blocks) + "\n"


def render_types() -> str:
    """Extensions, then the enum types, generated from the same tuple the models use."""
    values = ", ".join(f"'{value}'" for value in DATASET_EMBEDDING_FIELDS)
    enum_sql = f"""-- ============================================
-- TYPES
-- ============================================

-- Named embeddings stored per dataset. The labels mapping generated in the
-- record_embeddings.labels column (tables.sql) is derived from the same list, so each value
-- always gets its own label number.
DO $$ BEGIN
    CREATE TYPE {DATASET_EMBEDDING_FIELD_ENUM} AS ENUM ({values});
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;"""
    return HEADER + "\n" + EXTENSIONS_SQL + "\n\n" + enum_sql + "\n"


def render_indexes(*metadatas: MetaData) -> str:
    """CREATE INDEX for every explicitly declared index.

    index_datasets.py splits this file on `;` and regex-matches `CREATE INDEX (\\w+)` per chunk to
    decide what to drop and rebuild around a bulk load, so keep one statement per index and never
    write the words CREATE INDEX inside a comment here.
    """
    statements = []
    for metadata in metadatas:
        for table in metadata.sorted_tables:
            statements += [render(CreateIndex(index)) + ";" for index in sorted(table.indexes, key=lambda i: i.name)]
    return HEADER + "\n" + "\n\n".join(statements) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("out_path", nargs="?", type=Path, help="single output file with the tables only")
    parser.add_argument("--out-dir", type=Path, help="write types.sql, tables.sql and indexes.sql into this directory")
    args = parser.parse_args()

    if args.out_dir:
        outputs = {
            args.out_dir / "types.sql": render_types(),
            args.out_dir / "tables.sql": render_tables(Base.metadata, SearchBase.metadata),
            # Search tables only: index_datasets.py creates every index of this file when
            # rebuilding, and it must not touch the app tables, which this service creates
            # itself (their indexes come with `Base.metadata.create_all`).
            args.out_dir / "indexes.sql": render_indexes(SearchBase.metadata),
        }
    else:
        outputs = {args.out_path or Path("schema.sql"): render_tables(Base.metadata, SearchBase.metadata)}

    for path, content in outputs.items():
        path.write_text(content)
        print(f"Wrote {path}")


if __name__ == "__main__":
    main()
